# Generated by Django 2.2 on 2020-04-28 16:22

from django.db import migrations, models
import storages.backends.dropbox


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0015_auto_20200428_1921'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='photo',
            field=models.ImageField(blank=True, default=None, storage=storages.backends.dropbox.DropBoxStorage(), upload_to=''),
        ),
    ]
