# Generated by Django 2.2 on 2020-04-30 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_auto_20200430_1801'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_image',
            field=models.ImageField(default='profile_image/default.jpg', upload_to=''),
        ),
    ]
