# Generated by Django 2.2 on 2020-04-30 21:24

import backend.account.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_auto_20200430_1803'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_image',
            field=models.ImageField(default='profile_image/default.jpg', upload_to=backend.account.models.path_and_rename),
        ),
    ]
